### ISSUE TITLE
Getting always timeouts

### ISSUE THREAD

**Issue by Mansi1** [ribeirogab/free-translate#15]
`         console.log('en', language, namespace, prepareTranslationKey);
          const translatedText = await translate(prepareTranslationKey, { from: 'en', to: language });
`

pl 404 Page ${{path}} was not found.
(node:5377) UnhandledPromiseRejectionWarning: Error: Error: .wait() for span[jsname=jqKxS] timed out after 60000msec

**Comment by Mansi1** [comment]
if i use nightmare with options
`const nightmare = new Nightmare({
      ignoreDownloads: true,
      show: true,
      waitTimeout: 60000,
    });`

thats a problem
<img width="454" alt="image" src="https://user-images.githubusercontent.com/12079044/153718523-58c2a6f5-d8de-485e-aa81-d67ea666ea85.png">

**Comment by Mansi1** [comment]
i created an pull request ;)

**Comment by ribeirogab** [comment]
tested and approved  ✅ 

new version with fix: [v0.6.1](https://www.npmjs.com/package/free-translate/v/0.6.1)

closing the issue, thanks @Mansi1!
